services:
  laravel:
    build:
      args:
        user: kreoin
        uid: 1000
      context: ./backend
    image: laravel
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - chat-network

  vue:
    build:
      context: ./frontend
    tty: true
    container_name: vue
    working_dir: /var/www
    volumes:
      - .:/var/www # Монтируем локальную папку в контейнер как /var/www
    networks:
      - chat-network

  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chat-network
    depends_on:
      - laravel
      - vue
networks:
  chat-network:
    driver: bridge
